import type { Locale } from "./localization";

type SiteCopy = {
  tridentAlt: string;
  heroTitle: string;
  heroSubtitle: string;
  jumpToLabel: string;
  categoryCountLabelSingle: string;
  categoryCountLabelPlural: string;
  featuredLabel: string;
  sourcesLabel: string;
  copyableLinkLabel: string;
  footerMotto: string;
  footerNote: string;
  githubLinkLabel: string;
  languageToggleLabel: string;
  languageNames: Record<Locale, string>;
  metaStats: Array<{
    num: string;
    label: string;
  }>;
  filters: {
    all: string;
  };
};

export const SITE_COPY = {
  en: {
    tridentAlt: "Ukrainian trident",
    heroTitle: "Ukraine",
    heroSubtitle: "A Journey Through Time, Culture, and Resilience",
    jumpToLabel: "Jump to",
    categoryCountLabelSingle: "item in this category",
    categoryCountLabelPlural: "items in this category",
    featuredLabel: "Featured",
    sourcesLabel: "Sources",
    copyableLinkLabel: "Copyable link",
    footerMotto: "Slava Ukraini - Glory to Ukraine",
    footerNote: "Images generated by AI.",
    githubLinkLabel: "View Project on GitHub",
    languageToggleLabel: "Language",
    languageNames: {
      en: "English",
      uk: "Ukrainian",
    },
    metaStats: [
      {
        num: "1,000+",
        label: "Years of History",
      },
      {
        num: "24",
        label: "UNESCO Assets",
      },
      {
        num: "7",
        label: "Bordering Countries",
      },
    ],
    filters: {
      all: "All",
    },
  },
  uk: {
    tridentAlt: "Український тризуб",
    heroTitle: "Україна",
    heroSubtitle: "Подорож крізь час, культуру та незламність",
    jumpToLabel: "Перейти до",
    categoryCountLabelSingle: "елемент у цій категорії",
    categoryCountLabelPlural: "елементи у цій категорії",
    featuredLabel: "Обране",
    sourcesLabel: "Джерела",
    copyableLinkLabel: "Посилання на елемент",
    footerMotto: "Слава Україні - Героям слава",
    footerNote: "Зображення згенеровано ШІ.",
    githubLinkLabel: "Переглянути проєкт на GitHub",
    languageToggleLabel: "Мова",
    languageNames: {
      en: "Англійська",
      uk: "Українська",
    },
    metaStats: [
      {
        num: "1,000+",
        label: "Років історії",
      },
      {
        num: "24",
        label: "Об'єктів UNESCO",
      },
      {
        num: "7",
        label: "Сусідніх країн",
      },
    ],
    filters: {
      all: "Усі",
    },
  },
} satisfies Record<Locale, SiteCopy>;
